### ISSUE TITLE
ClientGateway

### ISSUE THREAD

**Issue by michaeleino** [ARPU-PLUS/Connekio#10]
this need to be renovated, we can now submit/receive all the SMSCs to the same port.

either to be removed or to be added to the Operator creation page for future usage if any.

![screenshot from 2018-04-22 17-52-04](https://user-images.githubusercontent.com/6287237/39096936-f08a72be-4655-11e8-91f7-3be2e4816beb.png)

**Comment by michaeleino** [comment]
still need to discuss, what will happen here

**Comment by SalahNourElDin** [comment]
Dear All,
kindly be informed that we will discuss the issue tomorrow morning ISA 
Thanks,
