### ISSUE TITLE
Profiles Category not available

### ISSUE THREAD

**Issue by michaeleino** [ARPU-PLUS/Connekio#12]
created a new category "SR"
![screenshot from 2018-04-22 18-05-50](https://user-images.githubusercontent.com/6287237/39097126-7d23d70e-4658-11e8-91b8-dc6af6bb8355.png)

can't create a routing/selling profile for it:
![20180422_181449](https://user-images.githubusercontent.com/6287237/39097180-4c4da668-4659-11e8-8f71-b7e2bcb00e49.jpg)

**Comment by Michaelfarouk78** [comment]
still  existing  I created profile type "mfarouk" under Profile category  and go try to create routing profile + can't find the new type "mfarouk" under Type

![Picture1.jpg](https://images.zenhubusercontent.com/5ad7293b4b5806bc2bcf99c1/d567ccc6-4718-46e2-8d7f-aa9346a91607)

![Picture2.jpg](https://images.zenhubusercontent.com/5ad7293b4b5806bc2bcf99c1/b9588285-3e17-4da3-b6f3-856a2ce16b59)

**Comment by SalahNourElDin** [comment]
check

**Comment by Michaelfarouk78** [comment]
It's Solved

**Comment by michaeleino** [comment]
new profile not available on the "Connections Senders" view page

![screenshot from 2018-04-29 18-35-16](https://user-images.githubusercontent.com/6287237/39408834-e0982e50-4bdc-11e8-8cb9-ae76c2a3a4ff.png)

**Comment by SalahNourElDin** [comment]
above category only under Vodafone.
