### ISSUE TITLE
Connections Senders browsing

### ISSUE THREAD

**Issue by michaeleino** [ARPU-PLUS/Connekio#16]
need to show the available senders per operator/type for all connections...

also need to export the result.

![screenshot from 2018-04-22 18-43-09](https://user-images.githubusercontent.com/6287237/39097492-2e5a6aac-465d-11e8-94c2-47eac03f0c01.png)

**Comment by michaeleino** [comment]
need to add the connection column to the result, to have more sense.

![screenshot from 2018-04-23 17-48-05](https://user-images.githubusercontent.com/6287237/39137678-822e788c-471e-11e8-8004-9de2a7ea53fd.png)

**Comment by SalahNourElDin** [comment]
Done please review and mark it as solved if solve

**Comment by michaeleino** [comment]
look great (Y)
