### ISSUE TITLE
can't create routing profile

### ISSUE THREAD

**Issue by michaeleino** [ARPU-PLUS/Connekio#20]
using attached sheet, we can't create a new profile.

[ProfileDataad636360-2494-4d12-aaef-5cdeb25072ee.csv.zip](https://github.com/ARPU-PLUS/Connekio/files/1938990/ProfileDataad636360-2494-4d12-aaef-5cdeb25072ee.csv.zip)

![screenshot from 2018-04-23 17-36-53](https://user-images.githubusercontent.com/6287237/39137111-1adea446-471d-11e8-8614-58bf0317fe6d.png)

**Comment by SalahNourElDin** [comment]
Please don't change column format or names because Priority  column readed as "Priority" so please download sheet as default and upload as default without any change into it

**Comment by Michaelfarouk78** [comment]
It's solved
