### ISSUE TITLE
Operator connection exception

### ISSUE THREAD

**Issue by michaeleino** [ARPU-PLUS/Connekio#21]
just created some profile types, then go to create SMPPout connection and press the template export.
blowing the below exception:

![screenshot from 2018-04-23 18-13-00](https://user-images.githubusercontent.com/6287237/39139448-3e835a2c-4722-11e8-9e71-6f9166060ae7.png)

**Comment by SalahNourElDin** [comment]
try now i fixed it please check and mark it as solved .

**Comment by SalahNourElDin** [comment]
for next issues please assign it to me because this not assigned

**Comment by Michaelfarouk78** [comment]
Export Template it's solved
