### ISSUE TITLE
Speedflow sim traffic to Egypt not updated although price notification received

### ISSUE THREAD

**Issue by ShadyAz** [ARPU-PLUS/Connekio#25]
Price for Spdflow_SR is still 0.0053 while price notification received with 0.01

**Comment by SalahNourElDin** [comment]
which connection ?

**Comment by ShadyAz** [comment]
EGY_Etisalat_Speedflow_SR
EGY_Orange_Speedflow_SR
EGY_Vodafone_Speedflow_SR

**Comment by SalahNourElDin** [comment]
Repeated Connections Found please check mail with subject "Repeated Connections"

**Comment by ShadyAz** [comment]
Dears, plz check Salah's comment

**Comment by Michaelfarouk78** [comment]
Dear Salah,

Please remove the repeated connections after check if the connection assigned to client or not.

EGY_Etisalat_Speedflow_SR 
EGY_Orange_Speedflow_SR 
EGY_Vodafone_Speedflow_SR

**Comment by SalahNourElDin** [comment]
Removed
