### ISSUE TITLE
Connection invisible

### ISSUE THREAD

**Issue by ShadyAz** [ARPU-PLUS/Connekio#31]
UAE_du_Globetele Services_Dir

**Comment by ShadyAz** [comment]
these are invisible too

Iran_MCI-TCI_Horisen_HQ
Iran_MCI-TCI_Broad Net Technologies_Dir
Iran_Rightel_Broad Net Technologies_Dir

**Comment by ShadyAz** [comment]
And those

Egy_Vodafone_BSG_SR
Bang_Robi_BSG_SR
Bang_Robi_Speedflow_SR
Bang_Airtel_BSG_SR
Bang_banglalink (Orascom)_BSG_SR
Bang_Grameenphone_BSG_SR

**Comment by SalahNourElDin** [comment]
done check and mark issue as solved

**Comment by ShadyAz** [comment]
all are ok now, check this one
Moro_MarocTelecom_BSG_SR

**Comment by SalahNourElDin** [comment]
check
