### ISSUE TITLE
Connekio new release test and publish.

### ISSUE THREAD

**Issue by SalahNourElDin** [ARPU-PLUS/Connekio#34]

**Comment by SalahNourElDin** [comment]
Dears,
Please Test Connekio on the below link --> 10.2.10.242:10000
username & password like yours on connekio

**Comment by ShadyAz** [comment]
will I c the same data I've on current version? can I start working on it and modify live accounts

**Comment by ShadyAz** [comment]
i tried to add a new smpp account to broadnet and i pressed updated, now i cant find broadnet to know if the action was done successfully or not

**Comment by SalahNourElDin** [comment]
Dear Shady,
please create new accounts don't update existing accounts
