### ISSUE TITLE
Routing & Selling profiles not visible 

### ISSUE THREAD

**Issue by Michaelfarouk78** [ARPU-PLUS/Connekio#47]
Please check the Routing & selling profiles are not visible 

![Screenshot - 5_6_2018 , 2_42_13 PM.jpg](https://images.zenhubusercontent.com/5ad7293b4b5806bc2bcf99c1/171ce583-9d12-44e9-8b32-8243c19d4876)

**Comment by SalahNourElDin** [comment]
check please first before choose

**Comment by Michaelfarouk78** [comment]
done .. solved

Please Move the checkbox  first column.
