### ISSUE TITLE
Double Operator Connection Information 

### ISSUE THREAD

**Issue by Michaelfarouk78** [ARPU-PLUS/Connekio#48]
we can create duplicated Operator connection 

![Screenshot - 5_6_2018 , 3_58_07 PM.jpg](https://images.zenhubusercontent.com/5ad7293b4b5806bc2bcf99c1/e6db507d-aebc-403e-852b-28e2977ccfda)

**Comment by SalahNourElDin** [comment]
not same because there are difference in defaultsender,operatorconnectionid
