### ISSUE TITLE
Monty connections in lebanon

### ISSUE THREAD

**Issue by ShadyAz** [ARPU-PLUS/Connekio#54]
Dears,
Monty connection to alfa isn't visible
Leba_alfa_Monty Mobile_Dir

also Monty connection to MTC touch is linked to Alfa which is wrong

Leba_MTC_Touch_Monty Mobile_Dir

**Comment by SalahNourElDin** [comment]
done check please.

**Comment by ShadyAz** [comment]
solved for touch operator but still wrong mapping in Alfa
