### ISSUE TITLE
connection invisible

### ISSUE THREAD

**Issue by ShadyAz** [ARPU-PLUS/Connekio#62]
Paki_Warid_Horisen_HQ

**Comment by ShadyAz** [comment]
Kuwa_Viva_LankTel_HQ

**Comment by SalahNourElDin** [comment]
check it

**Comment by ShadyAz** [comment]
Syri_MTN_IT Decision_Dir

**Comment by ShadyAz** [comment]
Iraq_Zain_Lexico-SMS_Dir

**Comment by ShadyAz** [comment]
Iran_Rightel_LankTel_WS

**Comment by ShadyAz** [comment]
Iran_Rightel_Broad Net Technologies_WS

**Comment by ShadyAz** [comment]
Bang_Grameenphone_Routemobile_WS

**Comment by ShadyAz** [comment]
Bang_Grameenphone_LankTel_WS

**Comment by ShadyAz** [comment]
Bang_banglalink (Orascom)_LankTel_WS
Bang_Airtel_LankTel_WS
