### ISSUE TITLE
Operator Connection Filteration

### ISSUE THREAD

**Issue by SalahNourElDin** [ARPU-PLUS/Connekio#7]
Update existing smppoutconnection repeated to be only one connection then update it under operators

**Comment by SalahNourElDin** [comment]
[https://app.zenhub.com/files/130042250/26fdf8e4-f710-4566-adfb-ce7369ae9cb7/download](https://app.zenhub.com/files/130042250/26fdf8e4-f710-4566-adfb-ce7369ae9cb7/download)

Please Find attached sheet and filter it

**Comment by Michaelfarouk78** [comment]
We can't review more than 3K connections for the old platform, after migration we didn't need that the connection
